name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install
    
    - name: Run ESLint
      run: bun run lint

    - name: Run tests
      run: bun test

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/
        retention-days: 30

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## 更新内容

          请查看 [CHANGELOG.md](CHANGELOG.md) 了解详细更新内容。

          ## jsDelivr CDN 链接

          ### Wiki Vditor (推荐)
          ```html
          <script src="https://cdn.jsdelivr.net/gh/scutken/confluence-enhance@${{ github.ref_name }}/dist/wiki-vditor.min.js"></script>
          ```

          这是一个完整的单文件解决方案，包含所有依赖，无需额外的CSS文件。
        files: |
          dist/wiki-vditor.min.js
          dist/wiki-vditor.js
        draft: false
        prerelease: false
